// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen -source deps.go -destination deps_test.go -package list_divisions
//

// Package list_divisions is a generated GoMock package.
package list_divisions

import (
	context "context"
	reflect "reflect"

	models "github.com/amarin/genodex/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAdminDivisionRepo is a mock of AdminDivisionRepo interface.
type MockAdminDivisionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAdminDivisionRepoMockRecorder
	isgomock struct{}
}

// MockAdminDivisionRepoMockRecorder is the mock recorder for MockAdminDivisionRepo.
type MockAdminDivisionRepoMockRecorder struct {
	mock *MockAdminDivisionRepo
}

// NewMockAdminDivisionRepo creates a new mock instance.
func NewMockAdminDivisionRepo(ctrl *gomock.Controller) *MockAdminDivisionRepo {
	mock := &MockAdminDivisionRepo{ctrl: ctrl}
	mock.recorder = &MockAdminDivisionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminDivisionRepo) EXPECT() *MockAdminDivisionRepoMockRecorder {
	return m.recorder
}

// ChildrenOfDivision mocks base method.
func (m *MockAdminDivisionRepo) ChildrenOfDivision(ctx context.Context, parent models.ID, access models.Access, page models.Page) ([]*models.AdministrativeDivision, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChildrenOfDivision", ctx, parent, access, page)
	ret0, _ := ret[0].([]*models.AdministrativeDivision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChildrenOfDivision indicates an expected call of ChildrenOfDivision.
func (mr *MockAdminDivisionRepoMockRecorder) ChildrenOfDivision(ctx, parent, access, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChildrenOfDivision", reflect.TypeOf((*MockAdminDivisionRepo)(nil).ChildrenOfDivision), ctx, parent, access, page)
}

// GetCitation mocks base method.
func (m *MockAdminDivisionRepo) GetCitation(ctx context.Context, id models.ID) (*models.Citation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCitation", ctx, id)
	ret0, _ := ret[0].(*models.Citation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCitation indicates an expected call of GetCitation.
func (mr *MockAdminDivisionRepoMockRecorder) GetCitation(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCitation", reflect.TypeOf((*MockAdminDivisionRepo)(nil).GetCitation), ctx, id)
}

// ListAdministrativeDivisions mocks base method.
func (m *MockAdminDivisionRepo) ListAdministrativeDivisions(ctx context.Context, access models.Access, page models.Page) ([]*models.AdministrativeDivision, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAdministrativeDivisions", ctx, access, page)
	ret0, _ := ret[0].([]*models.AdministrativeDivision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAdministrativeDivisions indicates an expected call of ListAdministrativeDivisions.
func (mr *MockAdminDivisionRepoMockRecorder) ListAdministrativeDivisions(ctx, access, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAdministrativeDivisions", reflect.TypeOf((*MockAdminDivisionRepo)(nil).ListAdministrativeDivisions), ctx, access, page)
}
