// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen -source deps.go -destination deps_test.go -package create_division
//

// Package create_division is a generated GoMock package.
package create_division

import (
	context "context"
	reflect "reflect"

	models "github.com/amarin/genodex/internal/models"
	store "github.com/amarin/genodex/internal/store"
	gomock "go.uber.org/mock/gomock"
)

// MockDivisionStore is a mock of DivisionStore interface.
type MockDivisionStore struct {
	ctrl     *gomock.Controller
	recorder *MockDivisionStoreMockRecorder
	isgomock struct{}
}

// MockDivisionStoreMockRecorder is the mock recorder for MockDivisionStore.
type MockDivisionStoreMockRecorder struct {
	mock *MockDivisionStore
}

// NewMockDivisionStore creates a new mock instance.
func NewMockDivisionStore(ctrl *gomock.Controller) *MockDivisionStore {
	mock := &MockDivisionStore{ctrl: ctrl}
	mock.recorder = &MockDivisionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDivisionStore) EXPECT() *MockDivisionStoreMockRecorder {
	return m.recorder
}

// InTx mocks base method.
func (m *MockDivisionStore) InTx(ctx context.Context, fn func(store.Store) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// InTx indicates an expected call of InTx.
func (mr *MockDivisionStoreMockRecorder) InTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InTx", reflect.TypeOf((*MockDivisionStore)(nil).InTx), ctx, fn)
}

// MockIDGenerator is a mock of IDGenerator interface.
type MockIDGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockIDGeneratorMockRecorder
	isgomock struct{}
}

// MockIDGeneratorMockRecorder is the mock recorder for MockIDGenerator.
type MockIDGeneratorMockRecorder struct {
	mock *MockIDGenerator
}

// NewMockIDGenerator creates a new mock instance.
func NewMockIDGenerator(ctrl *gomock.Controller) *MockIDGenerator {
	mock := &MockIDGenerator{ctrl: ctrl}
	mock.recorder = &MockIDGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDGenerator) EXPECT() *MockIDGeneratorMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *MockIDGenerator) New(t models.Type) models.ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", t)
	ret0, _ := ret[0].(models.ID)
	return ret0
}

// New indicates an expected call of New.
func (mr *MockIDGeneratorMockRecorder) New(t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockIDGenerator)(nil).New), t)
}
