// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen -source deps.go -destination deps_test.go -package list_settlements
//

// Package list_settlements is a generated GoMock package.
package list_settlements

import (
	reflect "reflect"

	models "github.com/amarin/genodex/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAdminDivisionRepo is a mock of AdminDivisionRepo interface.
type MockAdminDivisionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAdminDivisionRepoMockRecorder
	isgomock struct{}
}

// MockAdminDivisionRepoMockRecorder is the mock recorder for MockAdminDivisionRepo.
type MockAdminDivisionRepoMockRecorder struct {
	mock *MockAdminDivisionRepo
}

// NewMockAdminDivisionRepo creates a new mock instance.
func NewMockAdminDivisionRepo(ctrl *gomock.Controller) *MockAdminDivisionRepo {
	mock := &MockAdminDivisionRepo{ctrl: ctrl}
	mock.recorder = &MockAdminDivisionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminDivisionRepo) EXPECT() *MockAdminDivisionRepoMockRecorder {
	return m.recorder
}

// ListAdministrativeDivisions mocks base method.
func (m *MockAdminDivisionRepo) ListAdministrativeDivisions() ([]*models.AdministrativeDivision, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAdministrativeDivisions")
	ret0, _ := ret[0].([]*models.AdministrativeDivision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAdministrativeDivisions indicates an expected call of ListAdministrativeDivisions.
func (mr *MockAdminDivisionRepoMockRecorder) ListAdministrativeDivisions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAdministrativeDivisions", reflect.TypeOf((*MockAdminDivisionRepo)(nil).ListAdministrativeDivisions))
}
