// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen -source deps.go -destination deps_test.go -package store
//

// Package store is a generated GoMock package.
package store

import (
	reflect "reflect"

	models "github.com/amarin/genodex/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// GetAdministrativeDivision mocks base method.
func (m *MockStore) GetAdministrativeDivision(id models.ID) (*models.AdministrativeDivision, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdministrativeDivision", id)
	ret0, _ := ret[0].(*models.AdministrativeDivision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdministrativeDivision indicates an expected call of GetAdministrativeDivision.
func (mr *MockStoreMockRecorder) GetAdministrativeDivision(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdministrativeDivision", reflect.TypeOf((*MockStore)(nil).GetAdministrativeDivision), id)
}

// GetArchive mocks base method.
func (m *MockStore) GetArchive(id models.ID) (*models.Archive, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArchive", id)
	ret0, _ := ret[0].(*models.Archive)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArchive indicates an expected call of GetArchive.
func (mr *MockStoreMockRecorder) GetArchive(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArchive", reflect.TypeOf((*MockStore)(nil).GetArchive), id)
}

// GetArchiveDocument mocks base method.
func (m *MockStore) GetArchiveDocument(id models.ID) (*models.ArchiveDocument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArchiveDocument", id)
	ret0, _ := ret[0].(*models.ArchiveDocument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArchiveDocument indicates an expected call of GetArchiveDocument.
func (mr *MockStoreMockRecorder) GetArchiveDocument(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArchiveDocument", reflect.TypeOf((*MockStore)(nil).GetArchiveDocument), id)
}

// GetArchiveNode mocks base method.
func (m *MockStore) GetArchiveNode(id models.ID) (*models.ArchiveNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArchiveNode", id)
	ret0, _ := ret[0].(*models.ArchiveNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArchiveNode indicates an expected call of GetArchiveNode.
func (mr *MockStoreMockRecorder) GetArchiveNode(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArchiveNode", reflect.TypeOf((*MockStore)(nil).GetArchiveNode), id)
}

// GetAttachment mocks base method.
func (m *MockStore) GetAttachment(id models.ID) (*models.Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttachment", id)
	ret0, _ := ret[0].(*models.Attachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttachment indicates an expected call of GetAttachment.
func (mr *MockStoreMockRecorder) GetAttachment(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttachment", reflect.TypeOf((*MockStore)(nil).GetAttachment), id)
}

// GetChurch mocks base method.
func (m *MockStore) GetChurch(id models.ID) (*models.Church, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChurch", id)
	ret0, _ := ret[0].(*models.Church)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChurch indicates an expected call of GetChurch.
func (mr *MockStoreMockRecorder) GetChurch(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChurch", reflect.TypeOf((*MockStore)(nil).GetChurch), id)
}

// GetCitation mocks base method.
func (m *MockStore) GetCitation(id models.ID) (*models.Citation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCitation", id)
	ret0, _ := ret[0].(*models.Citation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCitation indicates an expected call of GetCitation.
func (mr *MockStoreMockRecorder) GetCitation(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCitation", reflect.TypeOf((*MockStore)(nil).GetCitation), id)
}

// GetEstate mocks base method.
func (m *MockStore) GetEstate(id models.ID) (*models.Estate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEstate", id)
	ret0, _ := ret[0].(*models.Estate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEstate indicates an expected call of GetEstate.
func (mr *MockStoreMockRecorder) GetEstate(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEstate", reflect.TypeOf((*MockStore)(nil).GetEstate), id)
}

// GetEvent mocks base method.
func (m *MockStore) GetEvent(id models.ID) (*models.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvent", id)
	ret0, _ := ret[0].(*models.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvent indicates an expected call of GetEvent.
func (mr *MockStoreMockRecorder) GetEvent(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvent", reflect.TypeOf((*MockStore)(nil).GetEvent), id)
}

// GetFamily mocks base method.
func (m *MockStore) GetFamily(id models.ID) (*models.Family, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFamily", id)
	ret0, _ := ret[0].(*models.Family)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFamily indicates an expected call of GetFamily.
func (mr *MockStoreMockRecorder) GetFamily(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFamily", reflect.TypeOf((*MockStore)(nil).GetFamily), id)
}

// GetGivenName mocks base method.
func (m *MockStore) GetGivenName(id models.ID) (*models.GivenName, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGivenName", id)
	ret0, _ := ret[0].(*models.GivenName)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGivenName indicates an expected call of GetGivenName.
func (mr *MockStoreMockRecorder) GetGivenName(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGivenName", reflect.TypeOf((*MockStore)(nil).GetGivenName), id)
}

// GetNote mocks base method.
func (m *MockStore) GetNote(id models.ID) (*models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNote", id)
	ret0, _ := ret[0].(*models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNote indicates an expected call of GetNote.
func (mr *MockStoreMockRecorder) GetNote(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNote", reflect.TypeOf((*MockStore)(nil).GetNote), id)
}

// GetParish mocks base method.
func (m *MockStore) GetParish(id models.ID) (*models.Parish, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParish", id)
	ret0, _ := ret[0].(*models.Parish)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParish indicates an expected call of GetParish.
func (mr *MockStoreMockRecorder) GetParish(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParish", reflect.TypeOf((*MockStore)(nil).GetParish), id)
}

// GetPatronymic mocks base method.
func (m *MockStore) GetPatronymic(id models.ID) (*models.Patronymic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPatronymic", id)
	ret0, _ := ret[0].(*models.Patronymic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPatronymic indicates an expected call of GetPatronymic.
func (mr *MockStoreMockRecorder) GetPatronymic(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPatronymic", reflect.TypeOf((*MockStore)(nil).GetPatronymic), id)
}

// GetPerson mocks base method.
func (m *MockStore) GetPerson(id models.ID) (*models.Person, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPerson", id)
	ret0, _ := ret[0].(*models.Person)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPerson indicates an expected call of GetPerson.
func (mr *MockStoreMockRecorder) GetPerson(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPerson", reflect.TypeOf((*MockStore)(nil).GetPerson), id)
}

// GetRelation mocks base method.
func (m *MockStore) GetRelation(id models.ID) (*models.Relation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelation", id)
	ret0, _ := ret[0].(*models.Relation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRelation indicates an expected call of GetRelation.
func (mr *MockStoreMockRecorder) GetRelation(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelation", reflect.TypeOf((*MockStore)(nil).GetRelation), id)
}

// GetRepository mocks base method.
func (m *MockStore) GetRepository(id models.ID) (*models.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepository", id)
	ret0, _ := ret[0].(*models.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepository indicates an expected call of GetRepository.
func (mr *MockStoreMockRecorder) GetRepository(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepository", reflect.TypeOf((*MockStore)(nil).GetRepository), id)
}

// GetResidence mocks base method.
func (m *MockStore) GetResidence(id models.ID) (*models.Residence, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResidence", id)
	ret0, _ := ret[0].(*models.Residence)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResidence indicates an expected call of GetResidence.
func (mr *MockStoreMockRecorder) GetResidence(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResidence", reflect.TypeOf((*MockStore)(nil).GetResidence), id)
}

// GetSource mocks base method.
func (m *MockStore) GetSource(id models.ID) (*models.Source, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSource", id)
	ret0, _ := ret[0].(*models.Source)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSource indicates an expected call of GetSource.
func (mr *MockStoreMockRecorder) GetSource(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSource", reflect.TypeOf((*MockStore)(nil).GetSource), id)
}

// GetSurname mocks base method.
func (m *MockStore) GetSurname(id models.ID) (*models.Surname, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSurname", id)
	ret0, _ := ret[0].(*models.Surname)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSurname indicates an expected call of GetSurname.
func (mr *MockStoreMockRecorder) GetSurname(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSurname", reflect.TypeOf((*MockStore)(nil).GetSurname), id)
}

// GetTitle mocks base method.
func (m *MockStore) GetTitle(id models.ID) (*models.Title, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTitle", id)
	ret0, _ := ret[0].(*models.Title)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTitle indicates an expected call of GetTitle.
func (mr *MockStoreMockRecorder) GetTitle(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTitle", reflect.TypeOf((*MockStore)(nil).GetTitle), id)
}

// ListAdministrativeDivisions mocks base method.
func (m *MockStore) ListAdministrativeDivisions() ([]*models.AdministrativeDivision, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAdministrativeDivisions")
	ret0, _ := ret[0].([]*models.AdministrativeDivision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAdministrativeDivisions indicates an expected call of ListAdministrativeDivisions.
func (mr *MockStoreMockRecorder) ListAdministrativeDivisions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAdministrativeDivisions", reflect.TypeOf((*MockStore)(nil).ListAdministrativeDivisions))
}

// ListArchiveDocuments mocks base method.
func (m *MockStore) ListArchiveDocuments() ([]*models.ArchiveDocument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListArchiveDocuments")
	ret0, _ := ret[0].([]*models.ArchiveDocument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListArchiveDocuments indicates an expected call of ListArchiveDocuments.
func (mr *MockStoreMockRecorder) ListArchiveDocuments() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListArchiveDocuments", reflect.TypeOf((*MockStore)(nil).ListArchiveDocuments))
}

// ListArchiveNodes mocks base method.
func (m *MockStore) ListArchiveNodes() ([]*models.ArchiveNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListArchiveNodes")
	ret0, _ := ret[0].([]*models.ArchiveNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListArchiveNodes indicates an expected call of ListArchiveNodes.
func (mr *MockStoreMockRecorder) ListArchiveNodes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListArchiveNodes", reflect.TypeOf((*MockStore)(nil).ListArchiveNodes))
}

// ListArchives mocks base method.
func (m *MockStore) ListArchives() ([]*models.Archive, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListArchives")
	ret0, _ := ret[0].([]*models.Archive)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListArchives indicates an expected call of ListArchives.
func (mr *MockStoreMockRecorder) ListArchives() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListArchives", reflect.TypeOf((*MockStore)(nil).ListArchives))
}

// ListAttachments mocks base method.
func (m *MockStore) ListAttachments() ([]*models.Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAttachments")
	ret0, _ := ret[0].([]*models.Attachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAttachments indicates an expected call of ListAttachments.
func (mr *MockStoreMockRecorder) ListAttachments() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAttachments", reflect.TypeOf((*MockStore)(nil).ListAttachments))
}

// ListChurches mocks base method.
func (m *MockStore) ListChurches() ([]*models.Church, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChurches")
	ret0, _ := ret[0].([]*models.Church)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChurches indicates an expected call of ListChurches.
func (mr *MockStoreMockRecorder) ListChurches() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChurches", reflect.TypeOf((*MockStore)(nil).ListChurches))
}

// ListCitations mocks base method.
func (m *MockStore) ListCitations() ([]*models.Citation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCitations")
	ret0, _ := ret[0].([]*models.Citation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCitations indicates an expected call of ListCitations.
func (mr *MockStoreMockRecorder) ListCitations() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCitations", reflect.TypeOf((*MockStore)(nil).ListCitations))
}

// ListEstates mocks base method.
func (m *MockStore) ListEstates() ([]*models.Estate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEstates")
	ret0, _ := ret[0].([]*models.Estate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEstates indicates an expected call of ListEstates.
func (mr *MockStoreMockRecorder) ListEstates() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEstates", reflect.TypeOf((*MockStore)(nil).ListEstates))
}

// ListEvents mocks base method.
func (m *MockStore) ListEvents() ([]*models.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvents")
	ret0, _ := ret[0].([]*models.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockStoreMockRecorder) ListEvents() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockStore)(nil).ListEvents))
}

// ListFamilies mocks base method.
func (m *MockStore) ListFamilies() ([]*models.Family, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFamilies")
	ret0, _ := ret[0].([]*models.Family)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFamilies indicates an expected call of ListFamilies.
func (mr *MockStoreMockRecorder) ListFamilies() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFamilies", reflect.TypeOf((*MockStore)(nil).ListFamilies))
}

// ListGivenNames mocks base method.
func (m *MockStore) ListGivenNames() ([]*models.GivenName, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGivenNames")
	ret0, _ := ret[0].([]*models.GivenName)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGivenNames indicates an expected call of ListGivenNames.
func (mr *MockStoreMockRecorder) ListGivenNames() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGivenNames", reflect.TypeOf((*MockStore)(nil).ListGivenNames))
}

// ListNotes mocks base method.
func (m *MockStore) ListNotes() ([]*models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotes")
	ret0, _ := ret[0].([]*models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotes indicates an expected call of ListNotes.
func (mr *MockStoreMockRecorder) ListNotes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotes", reflect.TypeOf((*MockStore)(nil).ListNotes))
}

// ListParishes mocks base method.
func (m *MockStore) ListParishes() ([]*models.Parish, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListParishes")
	ret0, _ := ret[0].([]*models.Parish)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListParishes indicates an expected call of ListParishes.
func (mr *MockStoreMockRecorder) ListParishes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListParishes", reflect.TypeOf((*MockStore)(nil).ListParishes))
}

// ListPatronymics mocks base method.
func (m *MockStore) ListPatronymics() ([]*models.Patronymic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPatronymics")
	ret0, _ := ret[0].([]*models.Patronymic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPatronymics indicates an expected call of ListPatronymics.
func (mr *MockStoreMockRecorder) ListPatronymics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPatronymics", reflect.TypeOf((*MockStore)(nil).ListPatronymics))
}

// ListPeople mocks base method.
func (m *MockStore) ListPeople() ([]*models.Person, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPeople")
	ret0, _ := ret[0].([]*models.Person)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPeople indicates an expected call of ListPeople.
func (mr *MockStoreMockRecorder) ListPeople() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPeople", reflect.TypeOf((*MockStore)(nil).ListPeople))
}

// ListRelations mocks base method.
func (m *MockStore) ListRelations() ([]*models.Relation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRelations")
	ret0, _ := ret[0].([]*models.Relation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRelations indicates an expected call of ListRelations.
func (mr *MockStoreMockRecorder) ListRelations() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRelations", reflect.TypeOf((*MockStore)(nil).ListRelations))
}

// ListRepositories mocks base method.
func (m *MockStore) ListRepositories() ([]*models.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRepositories")
	ret0, _ := ret[0].([]*models.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRepositories indicates an expected call of ListRepositories.
func (mr *MockStoreMockRecorder) ListRepositories() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRepositories", reflect.TypeOf((*MockStore)(nil).ListRepositories))
}

// ListResidences mocks base method.
func (m *MockStore) ListResidences() ([]*models.Residence, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListResidences")
	ret0, _ := ret[0].([]*models.Residence)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListResidences indicates an expected call of ListResidences.
func (mr *MockStoreMockRecorder) ListResidences() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListResidences", reflect.TypeOf((*MockStore)(nil).ListResidences))
}

// ListSources mocks base method.
func (m *MockStore) ListSources() ([]*models.Source, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSources")
	ret0, _ := ret[0].([]*models.Source)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSources indicates an expected call of ListSources.
func (mr *MockStoreMockRecorder) ListSources() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSources", reflect.TypeOf((*MockStore)(nil).ListSources))
}

// ListSurnames mocks base method.
func (m *MockStore) ListSurnames() ([]*models.Surname, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSurnames")
	ret0, _ := ret[0].([]*models.Surname)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSurnames indicates an expected call of ListSurnames.
func (mr *MockStoreMockRecorder) ListSurnames() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSurnames", reflect.TypeOf((*MockStore)(nil).ListSurnames))
}

// ListTitles mocks base method.
func (m *MockStore) ListTitles() ([]*models.Title, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTitles")
	ret0, _ := ret[0].([]*models.Title)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTitles indicates an expected call of ListTitles.
func (mr *MockStoreMockRecorder) ListTitles() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTitles", reflect.TypeOf((*MockStore)(nil).ListTitles))
}

// SaveAdministrativeDivision mocks base method.
func (m *MockStore) SaveAdministrativeDivision(a *models.AdministrativeDivision) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAdministrativeDivision", a)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAdministrativeDivision indicates an expected call of SaveAdministrativeDivision.
func (mr *MockStoreMockRecorder) SaveAdministrativeDivision(a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAdministrativeDivision", reflect.TypeOf((*MockStore)(nil).SaveAdministrativeDivision), a)
}

// SaveArchive mocks base method.
func (m *MockStore) SaveArchive(a *models.Archive) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveArchive", a)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveArchive indicates an expected call of SaveArchive.
func (mr *MockStoreMockRecorder) SaveArchive(a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveArchive", reflect.TypeOf((*MockStore)(nil).SaveArchive), a)
}

// SaveArchiveDocument mocks base method.
func (m *MockStore) SaveArchiveDocument(d *models.ArchiveDocument) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveArchiveDocument", d)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveArchiveDocument indicates an expected call of SaveArchiveDocument.
func (mr *MockStoreMockRecorder) SaveArchiveDocument(d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveArchiveDocument", reflect.TypeOf((*MockStore)(nil).SaveArchiveDocument), d)
}

// SaveArchiveNode mocks base method.
func (m *MockStore) SaveArchiveNode(n *models.ArchiveNode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveArchiveNode", n)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveArchiveNode indicates an expected call of SaveArchiveNode.
func (mr *MockStoreMockRecorder) SaveArchiveNode(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveArchiveNode", reflect.TypeOf((*MockStore)(nil).SaveArchiveNode), n)
}

// SaveAttachment mocks base method.
func (m *MockStore) SaveAttachment(a *models.Attachment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAttachment", a)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAttachment indicates an expected call of SaveAttachment.
func (mr *MockStoreMockRecorder) SaveAttachment(a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAttachment", reflect.TypeOf((*MockStore)(nil).SaveAttachment), a)
}

// SaveChurch mocks base method.
func (m *MockStore) SaveChurch(c *models.Church) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveChurch", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveChurch indicates an expected call of SaveChurch.
func (mr *MockStoreMockRecorder) SaveChurch(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveChurch", reflect.TypeOf((*MockStore)(nil).SaveChurch), c)
}

// SaveCitation mocks base method.
func (m *MockStore) SaveCitation(c *models.Citation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCitation", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCitation indicates an expected call of SaveCitation.
func (mr *MockStoreMockRecorder) SaveCitation(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCitation", reflect.TypeOf((*MockStore)(nil).SaveCitation), c)
}

// SaveEstate mocks base method.
func (m *MockStore) SaveEstate(e *models.Estate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEstate", e)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEstate indicates an expected call of SaveEstate.
func (mr *MockStoreMockRecorder) SaveEstate(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEstate", reflect.TypeOf((*MockStore)(nil).SaveEstate), e)
}

// SaveEvent mocks base method.
func (m *MockStore) SaveEvent(e *models.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEvent", e)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEvent indicates an expected call of SaveEvent.
func (mr *MockStoreMockRecorder) SaveEvent(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEvent", reflect.TypeOf((*MockStore)(nil).SaveEvent), e)
}

// SaveFamily mocks base method.
func (m *MockStore) SaveFamily(f *models.Family) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFamily", f)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveFamily indicates an expected call of SaveFamily.
func (mr *MockStoreMockRecorder) SaveFamily(f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFamily", reflect.TypeOf((*MockStore)(nil).SaveFamily), f)
}

// SaveGivenName mocks base method.
func (m *MockStore) SaveGivenName(g *models.GivenName) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveGivenName", g)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveGivenName indicates an expected call of SaveGivenName.
func (mr *MockStoreMockRecorder) SaveGivenName(g any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveGivenName", reflect.TypeOf((*MockStore)(nil).SaveGivenName), g)
}

// SaveNote mocks base method.
func (m *MockStore) SaveNote(n *models.Note) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveNote", n)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveNote indicates an expected call of SaveNote.
func (mr *MockStoreMockRecorder) SaveNote(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveNote", reflect.TypeOf((*MockStore)(nil).SaveNote), n)
}

// SaveParish mocks base method.
func (m *MockStore) SaveParish(p *models.Parish) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveParish", p)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveParish indicates an expected call of SaveParish.
func (mr *MockStoreMockRecorder) SaveParish(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveParish", reflect.TypeOf((*MockStore)(nil).SaveParish), p)
}

// SavePatronymic mocks base method.
func (m *MockStore) SavePatronymic(p *models.Patronymic) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePatronymic", p)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePatronymic indicates an expected call of SavePatronymic.
func (mr *MockStoreMockRecorder) SavePatronymic(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePatronymic", reflect.TypeOf((*MockStore)(nil).SavePatronymic), p)
}

// SavePerson mocks base method.
func (m *MockStore) SavePerson(p *models.Person) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePerson", p)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePerson indicates an expected call of SavePerson.
func (mr *MockStoreMockRecorder) SavePerson(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePerson", reflect.TypeOf((*MockStore)(nil).SavePerson), p)
}

// SaveRelation mocks base method.
func (m *MockStore) SaveRelation(r *models.Relation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRelation", r)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRelation indicates an expected call of SaveRelation.
func (mr *MockStoreMockRecorder) SaveRelation(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRelation", reflect.TypeOf((*MockStore)(nil).SaveRelation), r)
}

// SaveRepository mocks base method.
func (m *MockStore) SaveRepository(r *models.Repository) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRepository", r)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRepository indicates an expected call of SaveRepository.
func (mr *MockStoreMockRecorder) SaveRepository(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRepository", reflect.TypeOf((*MockStore)(nil).SaveRepository), r)
}

// SaveResidence mocks base method.
func (m *MockStore) SaveResidence(r *models.Residence) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveResidence", r)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveResidence indicates an expected call of SaveResidence.
func (mr *MockStoreMockRecorder) SaveResidence(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveResidence", reflect.TypeOf((*MockStore)(nil).SaveResidence), r)
}

// SaveSource mocks base method.
func (m *MockStore) SaveSource(s *models.Source) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSource", s)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSource indicates an expected call of SaveSource.
func (mr *MockStoreMockRecorder) SaveSource(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSource", reflect.TypeOf((*MockStore)(nil).SaveSource), s)
}

// SaveSurname mocks base method.
func (m *MockStore) SaveSurname(s *models.Surname) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSurname", s)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSurname indicates an expected call of SaveSurname.
func (mr *MockStoreMockRecorder) SaveSurname(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSurname", reflect.TypeOf((*MockStore)(nil).SaveSurname), s)
}

// SaveTitle mocks base method.
func (m *MockStore) SaveTitle(t *models.Title) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTitle", t)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveTitle indicates an expected call of SaveTitle.
func (mr *MockStoreMockRecorder) SaveTitle(t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTitle", reflect.TypeOf((*MockStore)(nil).SaveTitle), t)
}
