// Code generated by MockGen. DO NOT EDIT.
// Source: internal/auth/deps.go
//
// Generated by this command:
//
//	mockgen -source internal/auth/deps.go -destination internal/auth/deps_test.go -package auth
//

// Package auth is a generated GoMock package.
package auth

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CountOwners mocks base method.
func (m *MockStore) CountOwners(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountOwners", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountOwners indicates an expected call of CountOwners.
func (mr *MockStoreMockRecorder) CountOwners(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountOwners", reflect.TypeOf((*MockStore)(nil).CountOwners), ctx)
}

// CreateAPIToken mocks base method.
func (m *MockStore) CreateAPIToken(ctx context.Context, t APIToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAPIToken", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAPIToken indicates an expected call of CreateAPIToken.
func (mr *MockStoreMockRecorder) CreateAPIToken(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAPIToken", reflect.TypeOf((*MockStore)(nil).CreateAPIToken), ctx, t)
}

// CreateInvite mocks base method.
func (m *MockStore) CreateInvite(ctx context.Context, i Invite) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvite", ctx, i)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateInvite indicates an expected call of CreateInvite.
func (mr *MockStoreMockRecorder) CreateInvite(ctx, i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvite", reflect.TypeOf((*MockStore)(nil).CreateInvite), ctx, i)
}

// CreateOwner mocks base method.
func (m *MockStore) CreateOwner(ctx context.Context, o Owner) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOwner", ctx, o)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOwner indicates an expected call of CreateOwner.
func (mr *MockStoreMockRecorder) CreateOwner(ctx, o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOwner", reflect.TypeOf((*MockStore)(nil).CreateOwner), ctx, o)
}

// CreateSession mocks base method.
func (m *MockStore) CreateSession(ctx context.Context, s Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockStoreMockRecorder) CreateSession(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockStore)(nil).CreateSession), ctx, s)
}

// DeleteSession mocks base method.
func (m *MockStore) DeleteSession(ctx context.Context, id ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockStoreMockRecorder) DeleteSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockStore)(nil).DeleteSession), ctx, id)
}

// GetAPIToken mocks base method.
func (m *MockStore) GetAPIToken(ctx context.Context, id ID) (*APIToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAPIToken", ctx, id)
	ret0, _ := ret[0].(*APIToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAPIToken indicates an expected call of GetAPIToken.
func (mr *MockStoreMockRecorder) GetAPIToken(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAPIToken", reflect.TypeOf((*MockStore)(nil).GetAPIToken), ctx, id)
}

// GetAPITokenByHash mocks base method.
func (m *MockStore) GetAPITokenByHash(ctx context.Context, hash string) (*APIToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAPITokenByHash", ctx, hash)
	ret0, _ := ret[0].(*APIToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAPITokenByHash indicates an expected call of GetAPITokenByHash.
func (mr *MockStoreMockRecorder) GetAPITokenByHash(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAPITokenByHash", reflect.TypeOf((*MockStore)(nil).GetAPITokenByHash), ctx, hash)
}

// GetInviteByHash mocks base method.
func (m *MockStore) GetInviteByHash(ctx context.Context, hash string) (*Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInviteByHash", ctx, hash)
	ret0, _ := ret[0].(*Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInviteByHash indicates an expected call of GetInviteByHash.
func (mr *MockStoreMockRecorder) GetInviteByHash(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInviteByHash", reflect.TypeOf((*MockStore)(nil).GetInviteByHash), ctx, hash)
}

// GetOwner mocks base method.
func (m *MockStore) GetOwner(ctx context.Context, id ID) (*Owner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOwner", ctx, id)
	ret0, _ := ret[0].(*Owner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOwner indicates an expected call of GetOwner.
func (mr *MockStoreMockRecorder) GetOwner(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOwner", reflect.TypeOf((*MockStore)(nil).GetOwner), ctx, id)
}

// GetOwnerByLogin mocks base method.
func (m *MockStore) GetOwnerByLogin(ctx context.Context, login string) (*Owner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOwnerByLogin", ctx, login)
	ret0, _ := ret[0].(*Owner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOwnerByLogin indicates an expected call of GetOwnerByLogin.
func (mr *MockStoreMockRecorder) GetOwnerByLogin(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOwnerByLogin", reflect.TypeOf((*MockStore)(nil).GetOwnerByLogin), ctx, login)
}

// GetSessionByAccessHash mocks base method.
func (m *MockStore) GetSessionByAccessHash(ctx context.Context, hash string) (*Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByAccessHash", ctx, hash)
	ret0, _ := ret[0].(*Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByAccessHash indicates an expected call of GetSessionByAccessHash.
func (mr *MockStoreMockRecorder) GetSessionByAccessHash(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByAccessHash", reflect.TypeOf((*MockStore)(nil).GetSessionByAccessHash), ctx, hash)
}

// GetSessionByRefreshHash mocks base method.
func (m *MockStore) GetSessionByRefreshHash(ctx context.Context, hash string) (*Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByRefreshHash", ctx, hash)
	ret0, _ := ret[0].(*Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByRefreshHash indicates an expected call of GetSessionByRefreshHash.
func (mr *MockStoreMockRecorder) GetSessionByRefreshHash(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByRefreshHash", reflect.TypeOf((*MockStore)(nil).GetSessionByRefreshHash), ctx, hash)
}

// ListAPITokens mocks base method.
func (m *MockStore) ListAPITokens(ctx context.Context, ownerID ID) ([]APIToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAPITokens", ctx, ownerID)
	ret0, _ := ret[0].([]APIToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAPITokens indicates an expected call of ListAPITokens.
func (mr *MockStoreMockRecorder) ListAPITokens(ctx, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAPITokens", reflect.TypeOf((*MockStore)(nil).ListAPITokens), ctx, ownerID)
}

// MarkInviteUsed mocks base method.
func (m *MockStore) MarkInviteUsed(ctx context.Context, id, by ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkInviteUsed", ctx, id, by)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkInviteUsed indicates an expected call of MarkInviteUsed.
func (mr *MockStoreMockRecorder) MarkInviteUsed(ctx, id, by any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkInviteUsed", reflect.TypeOf((*MockStore)(nil).MarkInviteUsed), ctx, id, by)
}

// ReplaceSession mocks base method.
func (m *MockStore) ReplaceSession(ctx context.Context, id ID, s Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceSession", ctx, id, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceSession indicates an expected call of ReplaceSession.
func (mr *MockStoreMockRecorder) ReplaceSession(ctx, id, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceSession", reflect.TypeOf((*MockStore)(nil).ReplaceSession), ctx, id, s)
}

// RevokeAPIToken mocks base method.
func (m *MockStore) RevokeAPIToken(ctx context.Context, id ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAPIToken", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAPIToken indicates an expected call of RevokeAPIToken.
func (mr *MockStoreMockRecorder) RevokeAPIToken(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAPIToken", reflect.TypeOf((*MockStore)(nil).RevokeAPIToken), ctx, id)
}

// TouchAPIToken mocks base method.
func (m *MockStore) TouchAPIToken(ctx context.Context, id ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TouchAPIToken", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// TouchAPIToken indicates an expected call of TouchAPIToken.
func (mr *MockStoreMockRecorder) TouchAPIToken(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TouchAPIToken", reflect.TypeOf((*MockStore)(nil).TouchAPIToken), ctx, id)
}

// UpdateOwnerPassword mocks base method.
func (m *MockStore) UpdateOwnerPassword(ctx context.Context, id ID, hash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOwnerPassword", ctx, id, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOwnerPassword indicates an expected call of UpdateOwnerPassword.
func (mr *MockStoreMockRecorder) UpdateOwnerPassword(ctx, id, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOwnerPassword", reflect.TypeOf((*MockStore)(nil).UpdateOwnerPassword), ctx, id, hash)
}
