// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen -source deps.go -destination deps_test.go -package get_division
//

// Package get_division is a generated GoMock package.
package get_division

import (
	context "context"
	reflect "reflect"

	models "github.com/amarin/genodex/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockDivisionRepo is a mock of DivisionRepo interface.
type MockDivisionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDivisionRepoMockRecorder
	isgomock struct{}
}

// MockDivisionRepoMockRecorder is the mock recorder for MockDivisionRepo.
type MockDivisionRepoMockRecorder struct {
	mock *MockDivisionRepo
}

// NewMockDivisionRepo creates a new mock instance.
func NewMockDivisionRepo(ctrl *gomock.Controller) *MockDivisionRepo {
	mock := &MockDivisionRepo{ctrl: ctrl}
	mock.recorder = &MockDivisionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDivisionRepo) EXPECT() *MockDivisionRepoMockRecorder {
	return m.recorder
}

// GetAdministrativeDivision mocks base method.
func (m *MockDivisionRepo) GetAdministrativeDivision(ctx context.Context, id models.ID) (*models.AdministrativeDivision, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdministrativeDivision", ctx, id)
	ret0, _ := ret[0].(*models.AdministrativeDivision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdministrativeDivision indicates an expected call of GetAdministrativeDivision.
func (mr *MockDivisionRepoMockRecorder) GetAdministrativeDivision(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdministrativeDivision", reflect.TypeOf((*MockDivisionRepo)(nil).GetAdministrativeDivision), ctx, id)
}

// GetCitation mocks base method.
func (m *MockDivisionRepo) GetCitation(ctx context.Context, id models.ID) (*models.Citation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCitation", ctx, id)
	ret0, _ := ret[0].(*models.Citation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCitation indicates an expected call of GetCitation.
func (mr *MockDivisionRepoMockRecorder) GetCitation(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCitation", reflect.TypeOf((*MockDivisionRepo)(nil).GetCitation), ctx, id)
}
