// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen -source deps.go -destination deps_test.go -package delete_division
//

// Package delete_division is a generated GoMock package.
package delete_division

import (
	context "context"
	reflect "reflect"

	models "github.com/amarin/genodex/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockDivisionRepo is a mock of DivisionRepo interface.
type MockDivisionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDivisionRepoMockRecorder
	isgomock struct{}
}

// MockDivisionRepoMockRecorder is the mock recorder for MockDivisionRepo.
type MockDivisionRepoMockRecorder struct {
	mock *MockDivisionRepo
}

// NewMockDivisionRepo creates a new mock instance.
func NewMockDivisionRepo(ctrl *gomock.Controller) *MockDivisionRepo {
	mock := &MockDivisionRepo{ctrl: ctrl}
	mock.recorder = &MockDivisionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDivisionRepo) EXPECT() *MockDivisionRepoMockRecorder {
	return m.recorder
}

// DeleteAdministrativeDivision mocks base method.
func (m *MockDivisionRepo) DeleteAdministrativeDivision(ctx context.Context, id models.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAdministrativeDivision", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAdministrativeDivision indicates an expected call of DeleteAdministrativeDivision.
func (mr *MockDivisionRepoMockRecorder) DeleteAdministrativeDivision(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAdministrativeDivision", reflect.TypeOf((*MockDivisionRepo)(nil).DeleteAdministrativeDivision), ctx, id)
}
